POST http://localhost:3333/events
Content-Type: application/json

{
  "title":"Anápoli a ffcidade Jair Júnior",
  "details":"Maior efvento online de programação do Brasil.",
  "maximumAttendees": 5
}
